exclude: 'benchmark|conf|data|docs|outputs'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [--maxkb=15000]
      - id: check-yaml

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black

  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          [
            '--in-place',
            '--remove-unused-variable',
            '--ignore-init-module-imports',
            '--imports=torch,torch_geometric,torch_scatter,torch_cluster,numpy,sklearn,scipy,torch_sparse,torch_points_kernels',
          ]
  - repo: https://github.com/kynan/nbstripout
    rev: master
    hooks:
      - id: nbstripout
        files: '.ipynb'

  - repo: https://github.com/CCInc/pre-commit-hooks.git
    rev: master
    hooks:
      - id: poetry-generate-requirements
