# @package training
defaults:
  - /training/default

epochs: 200
num_workers: 4
batch_size: 4

optim:
  base_lr: 1e-3
  bn_scheduler:
    bn_policy: "step_decay"
    params:
      bn_momentum: 0.5
      bn_decay: 0.5
      decay_step: 20
      bn_clip: 1e-2

wandb:
  project: scannet_object_detection
  notes: "Corrected box prediction"
  name: VoteNet
