# @package training
defaults:
  - /training/default

epochs: 6000
num_workers: 6
batch_size: 64

optim:
  bn_scheduler:
    bn_policy: "step_decay"
    params:
      bn_momentum: 0.1
      bn_decay: 0.9
      decay_step: 3000
      bn_clip: 1e-2

wandb:
  project: default
