# @package training
defaults:
  - /training/default

epochs: 300
num_workers: 2
batch_size: 8
optim:
  base_lr: 0.01
  grad_clip: 100
  optimizer:
    class: SGD
    params:
      momentum: 0.98
      lr: ${training.optim.base_lr} # The path is cut from training
      weight_decay: 1e-3
  bn_scheduler:
    bn_policy: "step_decay"
    params:
      bn_momentum: 0.02
      bn_decay: 0.9
      decay_step: 1000
      bn_clip: 1e-2

wandb:
  project: s3dis-benchmark
  notes: "rsconv baseline"
  name: "rsconv"
