# @package training
defaults:
  - /training/default
  - override optim/optimizer: SGD

epochs: 300
num_workers: 4
batch_size: 8
precompute_multi_scale: True

optim:
  base_lr: 0.01
  grad_clip: 100
  optimizer:
    momentum: 0.9
    weight_decay: 1e-4
    dampening: 0.1
  bn_scheduler:
    bn_policy: "step_decay"
    params:
      bn_momentum: 0.1
      bn_decay: 0.9
      decay_step: 20
      bn_clip: 1e-2
wandb: 
  project: scannet-benchmark
  notes: "KPConv benchmark training"
  name: "kpconv"
