# @package training
defaults:
  - /training/default

epochs: 300
num_workers: 4
batch_size: 8
optim:
  base_lr: 0.1
  grad_clip: -1
  optimizer:
    class: SGD
    params:
      momentum: 0.9
      lr: ${training.optim.base_lr} # The path is cut from training
      weight_decay: 1e-4
      dampening: 0.1
  bn_scheduler:
    bn_policy: "step_decay"
    params:
      bn_momentum: 0.02
      bn_decay: 1
      decay_step: 2000
      bn_clip: 1e-2

wandb:
  project: scannet-benchmark
  notes: "Minkowski baseline"
  name: "Res16UNet34"

# Ref: https://github.com/chrischoy/SpatioTemporalSegmentation/blob/master/config.py
